version: '3.8'

services:
  mihomo-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_BASE_URL=http://api.mihomo.me/sr_info_parsed
      # - FRONTEND_URL=http://localhost:5173,https://express-sf1m-173672-5-1369600074.sh.run.tcloudbase.com
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - DB_HOST=10.2.108.136
      - DB_PORT=3306
      - DB_USER=oscar
      - DB_PASSWORD=Xsr20021018!
      - DB_NAME=sr_quick

    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # 健康检查已在 Dockerfile 中定义，这里可以移除避免重复